"""
Cel: testy jednostkowe agregatora.
Zakres:
  - ingest: poprawne zliczanie IP/ścieżek/statusów/metod i czasu
  - top-N: poprawne sortowanie (stabilność przy remisach nieistotna)
  - histogram: bucket='hour' oraz 'day', poprawne klucze
  - błędy: n<1 -> ValueError; bucket != {'hour','day'} -> ValueError
  - regresja: ingest po reset() działa od zera
Dane: syntetyczne rekordy na podstawie kontraktu parse_line.
"""
import pytest
from src.analyzer.aggregator import StatsAggregator

def test_ingest_counts_ips_and_paths(): ...
def test_topn_ips_and_paths(): ...
def test_status_and_method_counts(): ...
def test_time_histogram_hour_and_day(): ...
def test_reset_clears_state(): ...
def test_invalid_top_raises_valueerror(): ...
def test_invalid_bucket_raises_valueerror(): ...
